ARG VERSION
ARG NEXUS_USERNAME
ARG NEXUS_PASSWORD

FROM bellsoft/liberica-openjdk-alpine:latest 
ARG VERSION
ARG NEXUS_USERNAME
ARG NEXUS_PASSWORD

RUN apk add --no-cache bash
RUN apk add --no-cache curl

WORKDIR /app

RUN curl -u ${NEXUS_USERNAME}:${NEXUS_PASSWORD} -o product-service.jar http://161.35.24.93:8081/repository/buy02-group/com/gritlab/buy01/product-service/${VERSION}/product-service-${VERSION}.jar

COPY wait-for-it.sh /wait-for-it.sh
COPY healthcheck.sh /healthcheck.sh
RUN chmod +x /wait-for-it.sh
RUN chmod +x /healthcheck.sh

HEALTHCHECK --interval=30s --timeout=10s --start-period=10s --retries=3 CMD [ "/healthcheck.sh", "product" ]

CMD ["/wait-for-it.sh", "kafka:9092", "--", "java", "-jar", "product-service.jar"]
