ARG VERSION
ARG NEXUS_USERNAME
ARG NEXUS_PASSWORD

FROM nginx:alpine
ARG VERSION
ARG NEXUS_USERNAME
ARG NEXUS_PASSWORD

RUN echo ${VERSION}

WORKDIR /usr/share/nginx/html
RUN rm -rf ./*

RUN apk add --no-cache curl

RUN curl -u ${NEXUS_USERNAME}:${NEXUS_PASSWORD} -o app.tgz "http://161.35.24.93:8081/repository/frontend-repo/buy-01/-/buy-01-${VERSION}.tgz" \
  && tar -xzvf app.tgz -C /tmp \
  && mv /tmp/package/dist/buy-01/* /usr/share/nginx/html \
  && rm -rf /tmp/package app.tgz
COPY nginx.conf /etc/nginx/conf.d/default.conf.template

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 80 443

ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
