ARG VERSION

FROM nginx:alpine
ARG VERSION

WORKDIR /usr/share/nginx/html
RUN rm -rf ./*

RUN apk add --no-cache curl

RUN curl -o app.tar "http://161.35.24.93:8081/repository/buy02-group/com/gritlab/buy01/frontend/${VERSION}/frontend-${VERSION}.tar" \
  && tar -xvf app.tar \
  && rm app.tar
COPY nginx.conf /etc/nginx/conf.d/default.conf.template

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 80 443

ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
